name: Publish Package to GitHub NPM Registry

on: 
  release:
    type: [published]
    
jobs:
    npm-package:
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: set up NodeJS 
          uses: actions/setup-node@v4
          with:
            node-version: "20.x"
            registry-url: "https://npm.pkg.github.com"
        - name: Install NPM
          run: npm install

        - name: publish to the npm registry
          run: npm publish          
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} #end
